version: '3.4'

services:
   contentmongodb:
        image: mongo
        container_name: "contentMongoDbContainer"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null        
        ports:
            - 27018:27017

   dfc.sitefinity.microservice.api:
    image: dfcsitefinitymicroserviceapi
    build:
      context: .
      dockerfile: DFC.Sitefinity.MicroService.API/Dockerfile
    depends_on:
            - contentmongodb

